/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_hello_HelloJNI */

#ifndef _Included_com_jni_hello_HelloJNI
#define _Included_com_jni_hello_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_hello_HelloJNI
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_hello_HelloJNI_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
